Lesson-4-1
Armanchi/react-cockatoo pull request #11
Opened 2023-04-21 13:45 UTC by Armanchi

2023-04-24 14:53 UTC, kramduckner requested changes
Nice work! It's super close and I'm not seeing any prop type warnings! Just a couple comments about ensuring the props are being used in the components

2023-04-24 14:53 UTC, kramduckner commented on src/Components/TodoContainer.js
> +TodoContainer.propTypes = {
I don't see these props being passed into TodoContainer (on line 9)

2023-04-24 14:53 UTC, kramduckner commented on src/Components/InputWithLabel.js
> +InputWithLabel.propTypes = {
todoTitle, handleTitleChange, children are the only props being defined for InputWithLabel (see line 4 in this file)

2023-04-24 17:31 UTC, Armanchi commented on src/Components/TodoContainer.js
> +TodoContainer.propTypes = {
I just pushed the changes!

2023-04-25 20:38 UTC, kramduckner commented on src/Components/TodoContainer.js
> +TodoContainer.propTypes = {
tytyty

2023-04-25 20:38 UTC, kramduckner approved these changes
Nicely Done!

2023-04-25 20:54 UTC, merged